openapi: 3.0.0
info:
  title: Fudo API
  version: 1.0.0
servers:
  - url: "/"
paths:
  /:
    get:
      summary: Get OpenAPI specification
      responses:
        '200':
          description: OpenAPI specification in YAML format
          content:
            application/x-yaml:
              schema:
                type: string
            text/yaml:
              schema:
                type: string
  /auth:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /AUTHORS:
    get:
      summary: Get authors information
      responses:
        '200':
          description: Authors file content
          content:
            text/plain:
              schema:
                type: string
  /products:
    post:
      summary: Create product asynchronously
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '202':
          description: Product creation accepted
          headers:
            Location:
              description: URL of the created product resource
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreateResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: List available products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        user:
          type: string
        password:
          type: string
      required:
        - user
        - password
    AuthResponse:
      type: object
      properties:
        token:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string
    ProductCreate:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    ProductCreateResponse:
      type: object
      properties:
        message:
          type: string
        id:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
